-- local shared = game:GetService("ReplicatedStorage")
-- local client = game:GetService("StarterPlayer")
local server = game:GetService("ServerScriptService")
local Board = require(server.Board)
print("Initializing...")
-- local gameElements = script.Parent:WaitForChild("GameElements")

-- local MouseInputsManager = client.StarterPlayerScripts:WaitForChild("MouseInputsManager")
-- MouseInputsManager.initialize()
Board.new({ 10, 10 }, 16, Vector3.new(0, 0, 0))
print("Ready!")
